// This file is generated by Sim IDX. Do not edit manually.
import { pgEnum } from "drizzle-orm/pg-core";
import * as t from "drizzle-orm/pg-core";
import { db, types, table } from "@duneanalytics/sim-idx";

export const quoterError = table("quoter_error", {
  reason: t.text('reason'),
})

export const quoterLowLevelError = table("quoter_low_level_error", {
  data: db.bytes('data'),
})

export const transfer = table("transfer", {
  fromAddress: db.address('from_address'),
  toAddress: db.address('to_address'),
  token: db.address('token'),
  value: db.uint256('value'),
  txHash: db.bytes32('tx_hash'),
  tokenContext: t.text('token_context'),
  blockNumber: db.uint256('block_number'),
  blockTimestamp: db.uint256('block_timestamp'),
  sell: t.boolean('sell'),
  factoryVersion: db.uint8('factory_version'),
  contractDeployerAddress: db.address('contract_deployer_address'),
})

export const transferV31 = table("transfer_v3_1", {
  fromAddress: db.address('from_address'),
  toAddress: db.address('to_address'),
  token: db.address('token'),
  value: db.uint256('value'),
  txHash: db.bytes32('tx_hash'),
  tokenContext: t.text('token_context'),
  blockNumber: db.uint256('block_number'),
  blockTimestamp: db.uint256('block_timestamp'),
  sell: t.boolean('sell'),
  factoryVersion: t.text('factory_version'),
  contractDeployerAddress: db.address('contract_deployer_address'),
})
